
version: 2

models:
    - name: first_source
      description: "Transformation for source1"

    - name: second_source
      description: "Transformation for source 2"

    - name: third_source
      description: "Transformation for source 3"

    - name: lead_source
      description: "Transformation for salesforce leads"